const URL = {
  connURL: "/data/conn",
  confURL: "/data/conn/conf",
  indexURL: "/data/conn/sync",
  routeDisplayURL: "",
  vectorTileDisplayURL: "http://localhost:63343/vectorStyle_ol/index.html?_ijt=5rp6k0vfngju0ma7hptdoaj763",
  vectorMakeDisplayURL: "",
  allhistory:"/data/conn/sync/history",
  singlehistory:"/data/conn/sync/history",
  loginURL:"/log/login",
  opURL:"/log/op",
  allhistoryfilter:"/data/conn/sync/history",
  userParallelJobUrl:"/model/record",
  modelMonitorUrl: '/model/yarn/state',
  downloadModel: '/model/result/download',
  killcondition:'/model/yarn/kill',
  submitURL: "/model/yarn/submit",
  publicModelUrl: '/model',
  modelInfoUrl: '/model',
}
export default URL;
